### ISSUE TITLE
Configuration enclosed in categories.js "tabs" blocked is ignored 

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-play#1]
In the [showcase](http://quasar-framework.org/quasar-play/apple/index.html#!/showcase) page of the Quasar play app, configuration enclosed in "tabs" blocked configured in the categories.js file is ignored. Due to this problem, some features are not accessible from this showcase page (for example complex lists, multiline lists, etc.) even if we can access them directly by URL or by the quasar-framework.com website.

**Comment by rstoenescu** [comment]
That's intended. If on desktop, those tabs should not be displayed. Desktop version is shown for the official website (since website is accessed through a desktop browser). Those tabs are hidden because scrolling down the documentation page should only show demo with the related feature that's currently described at the top of the screen. Tabs are to be displayed only for the cordova version.
Please reopen if I missed a useful use-case.
